# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35fd0ee87cf3fa516af0d069963d50c27f2b2402ee0b6f2511831bae598502609fd6f79101f0e762aad37bb2fd1c7a2aba3672dfde9277412eb3faf984d894b6

test:
  secret_key_base: c48dcb2b7c05adffcc5f489a987cc3496d5998a49e2c57ef130901b37d0b85fd2dc9f180d55117faa1d1c3807c79dcbc14d6d9e5d4ac45795a80922634cc38a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
